# Generated by Django 5.0.3 on 2024-04-09 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_userprofile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pan',
            field=models.CharField(default='ABCDE1234F', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default='9876543210', max_length=10, unique=True),
        ),
    ]
